### ISSUE TITLE
5^2 doesn't equal 25, exponents don't seem to work.

### ISSUE THREAD

**Issue by LihrhaWolfe** [martindevans/Yolol#1]
![Capture](https://user-images.githubusercontent.com/15985460/59698987-c49dcb00-91be-11e9-9d64-f047db708568.PNG)

**Comment by martindevans** [comment]
<img width="140" alt="devenv_2019-06-18_23-53-04" src="https://user-images.githubusercontent.com/177519/59725098-4d028700-9224-11e9-9973-c5dc46b479aa.png">

Fixed ^_^
