### ISSUE TITLE
CI Test Runner

### ISSUE THREAD

**Issue by martindevans** [martindevans/Yolol#12]
Set up CI with a free service. See a list of free CI services [here](https://github.com/ligurio/awesome-ci).

**Comment by Leoltron** [comment]
I can set up Travis CI on fork by adding proper configuration file, but you'll need to add main repository from Travis Dashboard by your own (not to mention that build will be failing because of the tests). Will that be enough?

**Comment by Leoltron** [comment]
Nevermind, tests are passing (not locally though) https://travis-ci.com/Leoltron/Yolol/jobs/249293047

**Comment by thomasio101** [comment]
Hmmm.... a pull request of mine (#13) is yielding failing tests, @Leoltron. This is to be expected, though, as I'm making changes to some quite fundamental code.

**Comment by martindevans** [comment]
@Leoltron A setup with Travis would be perfect! If you get in a PR with the necessary configuration I'll add it to Travis once that's setup.
