### ISSUE TITLE
Boolean Analysis

### ISSUE THREAD

**Issue by martindevans** [martindevans/Yolol#18]
Build a CFG analysis pass that builds a set of `VariableName` which are known to be booleans (the result of any logical comparison).

This will need to run after SSA has been applied.

**Comment by thomasio101** [comment]
I'm interested in taking on this issue. ~But I do have a question, though: Where is SSA applied?~

**EDIT 2**  
Nevermind, I found it.

**Comment by martindevans** [comment]
You'll want to set up a test case something like this:

```
var p = TestExecutor.parse("program");
var cfg = new Builder(p).Build();
cfg = cfg.StaticSingleAssignment(out var ssa);

var booleans = cfg.FindBooleans();

// Assert correct things are in `booleans` set
```

If you want to print out the CFG for debugging purposes, do this:

```
cfg = cfg.MergeAdjacentBasicBlocks();
cfg = cfg.RemoveUnreachableBlocks();
Console.WriteLine(cfg.ToDot());
```

And paste dot code into [here](https://dreampuf.github.io/GraphvizOnline)
