### ISSUE TITLE
more a suggestion than an issue.

### ISSUE THREAD

**Issue by LihrhaWolfe** [martindevans/Yolol#2]
would it be possible to have an option to pass more than one .lol file to be run?  execution happens in the order of .lol file args passed, you can adjust the :vars from each of the files as they are called upon but all the files can share the same :vars.  this way people can simulate multiple chips running parallel or see how systems of chips would work together.

just a suggestion.

**Comment by martindevans** [comment]
Yeah that's something I've been thinking about, I'm not sure what the best way is to do it at the moment. I could do it as you suggest, basically doing something like:

```
foreach (var file in files)
    RunNextLine(file);
```

I think this could get quite confusing to understand what's going on though.

Another thing I have been considering is creating a network based system - one program can act as a master node (simulating the ship networking) and then you can connect as many yolol interpreters to that as you like (running each manually, line by line). This would also mean that people could write emulators for other machines which connect over the same network connections without requiring any special support by me.

**Comment by LihrhaWolfe** [comment]
so, just going to comment on this.  with the one program to run them all option, could you have it so that instead of going to each window to run the line, just have a single run line button you press on the main program to run one line in all the connected programs?

edit: forgot to mention that to negate, if there isn't already a way you have in mind to do so, just multiply the input by -1.

**Comment by martindevans** [comment]
I added a basic HTTP backed multi device network in with the latest commit. Check the readme for details.

This still requires you to manually run each line in each window, I may change how that works later (e.g. add an autorun option to the program which runs a line every 200ms like the game).
