### ISSUE TITLE
CommandLineParser not included in 2.0 release?

### ISSUE THREAD

**Issue by JakobCh** [martindevans/Yolol#24]
When I try to run "YololEmulator.exe" from the 2.0 release I get this message:
`Error:
  An assembly specified in the application dependencies manifest (YololEmulator.deps.json) was not found:
    package: 'CommandLineParser', version: '2.5.0'
    path: 'lib/netstandard2.0/CommandLine.dll'`

**Comment by JakobCh** [comment]
Seems like all the dependencies are missing, did you do a publish build?

**Comment by martindevans** [comment]
Thanks for reporting this, I'll investigate it this evening. version 2.0.0 was published in July so it's probably about time I put out a 3.0.0 version anyway!

**Comment by martindevans** [comment]
Hopefully this is fixed in the new release: https://github.com/martindevans/Yolol/releases/tag/3.0.0
