### ISSUE TITLE
reprinting lines

### ISSUE THREAD

**Issue by MrCitizen** [martindevans/Yolol#3]
So i'm not sure what is causing this but it's reprinting a line when instead it should be going to the next step after the condition was met.

My code is:

count = 0
if count < 3 then count++ goto 2 else goto 6 end

string = "hello world"

![mytest](https://user-images.githubusercontent.com/52061048/59897698-e57f3f80-93bb-11e9-9562-031cce2ffe8a.png)

So it doesn't actually run that line again because the condition is met, it reprints it, then the next step it runs the rest of the code.

**Comment by martindevans** [comment]
On closer inspection this looks like the correct behaviour:

```
[01] count = 0
State:
 | count = 0
=======================================================
[02] if count < 3 then count++ goto 2 else goto 6 end
State:
 | count = 1
// Incremented count, goto 2
=======================================================
[02] if count < 3 then count++ goto 2 else goto 6 end
State:
 | count = 2
// Incremented count, goto 2
=======================================================
[02] if count < 3 then count++ goto 2 else goto 6 end
State:
 | count = 3
// Incremented count, goto 2
=======================================================
[02] if count < 3 then count++ goto 2 else goto 6 end
State:
 | count = 3
// Do not increment count, goto 6
=======================================================
[06] string = "hello world"
State:
 | count = 3
 | string = "hello world"
```
