### ISSUE TITLE
Implement BaseUnaryExpression

### ISSUE THREAD

**Issue by martindevans** [martindevans/Yolol#4]
There is a [BaseBinaryExpression](https://github.com/martindevans/Yolol/blob/master/Yolol/Grammar/AST/Expressions/Binary/BaseBinaryExpression.cs) class which is the base of all binary expressions (e.g. [Add](https://github.com/martindevans/Yolol/blob/master/Yolol/Grammar/AST/Expressions/Binary/Add.cs), [Multiply](https://github.com/martindevans/Yolol/blob/master/Yolol/Grammar/AST/Expressions/Binary/Multiply.cs), [Or](https://github.com/martindevans/Yolol/blob/master/Yolol/Grammar/AST/Expressions/Binary/Or.cs), [EqualTo](https://github.com/martindevans/Yolol/blob/master/Yolol/Grammar/AST/Expressions/Binary/EqualTo.cs) etc). This class handles common things such as the left and Right subtrees. A similar `BaseUnaryExpression` could be written which handles the single `Child` expression.

Implement this, and base everything in [this folder](https://github.com/martindevans/Yolol/tree/master/Yolol/Grammar/AST/Expressions/Unary) on it.

**Comment by thomasio101** [comment]
I'm going to take on this issue.
